#!/bin/bash
#Install by "sudo cp modblock2 /usr/sbin;sudo touch /etc/modprobe.d/blacklist"

if [ "$1" != "-b" ] && [ "$1" != "-a" ] && [ "$1" != "-l" ] && [ "$1" != "-lc" ] && [ "$1" != "-lb" ] && [ "$1" != "-la" ] && [ "$1" != "-i" ]
then
	echo '''
 Kernel Module Blocker for Unix-like systems (Now Debian Only)
  You can use this script to block any kernel module.
  It -Simply- add it to the blacklist, And removes it when you "allow" it.
  Usage:
	-b  [mod] #to block any module
	-a  [mod] #to allow any blocked module
	-l        #to list all "Modules on System" and "Blocked Modules"
	-lc       #like previous but compact
	-lb       #to list blocked modules
	-la       #to list allowed modules
	-i        #to install this application to your system
	any thing else #to show this help ;)		
'''
exit
fi

blst='/etc/modprobe.d/blacklist'
touch $blst

function list {
	
	if [ "$1" == "blocked" ]
	then
		sed 's/.*[ ]//' $blst|grep -v '^$'
		exit
	elif [ "$1" == "allowed" ]
	then
		if [ -s $blst ]
		then
			lsmod|grep -v Module|sed 's/[ ].*//'|grep -v "`sed 's/.*[ ]//' $blst`"
		else
			lsmod|grep -v Module|sed 's/[ ].*//'
		fi
		exit
	fi
	
	echo "Modules on System:"
	a=`lsmod|grep -v Module|sed 's/[ ].*//'`
	if [ "$1" == "compact" ];then
		echo $a
	else		
		for i in $a
		do
			echo "  $i"
		done
	fi
	
	echo
	echo "Blocked Modules:"
	a=`sed 's/.*[ ]//' $blst`
	if [ -z "$a" ];then
		echo "  No modules were blocked";fi
	if [ "$1" == "compact" ];then
		echo $a
	else
		for i in $a
		do
			echo "  $i"
		done
	fi

}
for a in $@
do
	if [ "$a" == "-b" ]
	then
		case="block"
		continue
	elif [ "$a" == "-a" ]
	then
		case="allow"
		continue
	elif [ "$a" == "-l" ]
	then
		list
		continue
	elif [ "$a" == "-lc" ]
	then
		list compact
		continue
	elif [ "$a" == "-lb" ]
	then
		list blocked
		continue
	elif [ "$a" == "-la" ]
	then
		list allowed
		continue
	elif [ "$a" == "-i" ]
	then
		#cp $0 /usr/sbin
		cp $0 /usr/bin
		app=`echo $0|sed 's/.*\///'`
		chmod 0500 $app &>/dev/null
		echo "ModuleBlocker Installed"
		continue
	fi

	found=`lsmod|grep $a` #In Modules
	inbls=`cat $blst|grep $a` #In Blacklist

	if [ "$case" == "block" ]
	then
		if [ -z "$found" ];then
			echo "$a is not found on system"
		elif [ ! -z "$inbls" ];then
			echo "$a is already blocked"
		elif [ -z "$a" ];then
			echo "Nothing to block"
		else
			echo "blacklist" $a >> "$blst"		
			echo "blocked $a"
		fi
	elif [ "$case" == "allow" ]
	then
		if [ -z "$found" ];then
			echo "$a is not found on system"
		elif [ -z "$inbls" ];then
			echo "$a is not blocked"
		elif [ -z "$a" ];then
			echo "Nothing to allow"
		else
			sed "/$a/d" $blst > ${blst}.save
			mv ${blst}.save ${blst}
			echo "allowed $a"
		fi

	fi
done
exit