#!/bin/bash
#Install by "sudo cp modblock2 /usr/sbin;sudo touch /etc/modprobe.d/blacklist"

if [ "$1" != "-b" ] && [ "$1" != "-a" ] && [ "$1" != "-l" ]
then
	echo '''
 Kernel Module Blocker for Unix-like systems (Now Debian Only)
  You can use this script to block any kernel module.
  It -Simply- add it to the blacklist, And removes it when you "allow" it.
  Usage:
	-b  [mod] #to block any module
	-a  [mod] #to allow any blocked module
	-l        #to list all "Modules on System" and "Blocked Modules"
	-ll       #to list all modules like previous but per line
	any thing else #to show this help ;)		
'''
fi

blst='/etc/modprobe.d/blacklist'
if [ ! -f "$blst" ]
then
	touch $blst
fi

function list {
	modsys=`lsmod|grep -v Module|sed 's/[ ].*//'` #List Modules on System
	blkmod=`sed 's/.*[ ]//' $blst` #List Blacklist
	
	echo "Modules on System:"
	if [ "$1" == "line" ];then
		for i in $modsys;do echo $i;done
	else
		echo $modsys
	fi
	echo
	echo "Blocked Modules:"
	if [ "$blkmod" == "" ]
	then
		echo "  No modules were blocked"
	else
		if [ "$1" == "line" ];then
			for i in $blkmod;do echo $i;done
		else
			echo $blkmod
		fi
	fi
}
for a in $@
do		
	if [ "$a" == "-b" ]
	then
		case="block"
		continue
	elif [ "$a" == "-a" ]
	then
		case="allow"
		continue
	elif [ "$a" == "-l" ]
	then
		list
		continue
	elif [ "$a" == "-ll" ]
	then
		list line
		continue
	fi

	found=`lsmod|grep $a` #In Modules
	inbls=`cat $blst|grep $a` #In Blacklist

	if [ "$case" == "block" ]
	then
		if [ "$found" == "" ];then
			echo "$a is not found on system"
		elif [ "$inbls" != "" ];then
			echo "$a is already blocked"
		elif [ "$a" == "" ];then
			echo "Nothing to block"
		else
			echo "blacklist" $a >> "$blst"		
			echo "blocked $a"
		fi
	elif [ "$case" == "allow" ]
	then
		if [ "$found" == "" ];then
			echo "$a is not found on system"
		elif [ "$inbls" == "" ];then
			echo "$a is not blocked"
		elif [ "$a" == "" ];then
			echo "Nothing to allow"
		else
			sed "/$a/d" $blst > ${blst}.save
			mv ${blst}.save ${blst}
			echo "allowed $a"
		fi

	fi
done
exit