#!/bin/bash

# Shutdown, Restart, Suspend, or Hibernate the computer without sudo!
# Forked from https://gist.github.com/988104 to support delaying :)

usage() {
    echo "
 UserPower is a simple way to shutdown, restart, suspend
  or hibernate the computer without being root.
 Usage:
  $0 shutdown|restart|suspend|hibernate [minutes]
"
    exit
}

if [ -z $# ] ; then
    usage
elif [ ! -z "$2" ] ; then
    sleep ${2}m
fi

THINGY_UPOWER="dbus-send --system --print-reply --dest=org.freedesktop.UPower /org/freedesktop/UPower"
THINGY_CONSOLEKIT="dbus-send --system --print-reply --dest=org.freedesktop.ConsoleKit /org/freedesktop/ConsoleKit/Manager"
case $1 in
shutdown)
	echo Going to shutdown now ...
    $THINGY_CONSOLEKIT org.freedesktop.ConsoleKit.Manager.Stop >/dev/null
;;
restart)
        echo Going to restart now ...
    $THINGY_CONSOLEKIT org.freedesktop.ConsoleKit.Manager.Restart >/dev/null
;;
suspend)
        echo Going to suspend now ...
    $THINGY_UPOWER org.freedesktop.UPower.Suspend >/dev/null
;;
hibernate)
        echo Going to hibernate now ...
    $THINGY_UPOWER org.freedesktop.UPower.Hibernate >/dev/null
;;
*)
    usage
;;
esac

exit
