#!/bin/bash

# Shutdown, Restart, Suspend, or Hibernate the computer, and more, without sudo!
# Forked from https://gist.github.com/988104 to support delaying and more :)

usage() {
    echo "
 UserPower is a simple way to Shutdown, Restart, Suspend
  or Hibernate the Computer, and more, without being root
  or using difficult GUI.
   Usage:
  $0 logout|lockscreen|shutdown|restart|suspend|hibernate [minutes]
"
    exit
}

if [ -z $# ] ; then
    usage
elif [ ! -z "$2" ] ; then
    sleep ${2}m
fi

THINGY_UPOWER="dbus-send --system --print-reply --dest=org.freedesktop.UPower /org/freedesktop/UPower"
THINGY_CONSOLEKIT="dbus-send --system --print-reply --dest=org.freedesktop.ConsoleKit /org/freedesktop/ConsoleKit/Manager"
case $1 in
logout)
	echo Going to $1 now ...
    killall `w -f | grep tty | awk '{print $7 }'` >/dev/null
;;
lockscreen)
	echo Going to $1 now ...
    for i in `ls /usr/bin/*screensaver`; do if [ ! -z `pidof $i` ] ; then ${i}-command -l ; fi ;done >/dev/null
;;
shutdown)
	echo Going to $1 now ...
    $THINGY_CONSOLEKIT org.freedesktop.ConsoleKit.Manager.Stop >/dev/null
;;
restart)
        echo Going to $1 now ...
    $THINGY_CONSOLEKIT org.freedesktop.ConsoleKit.Manager.Restart >/dev/null
;;
suspend)
        echo Going to $1 now ...
    $THINGY_UPOWER org.freedesktop.UPower.Suspend >/dev/null
;;
hibernate)
        echo Going to $1 now ...
    $THINGY_UPOWER org.freedesktop.UPower.Hibernate >/dev/null
;;
*)
    usage
;;
esac

exit
