#!/bin/bash
# APTS: one tool to use apt-get, apt-cache, dpkg and dselect
# Notice that APTS is still ALPHA

# apts install package = apt-get install package
# apts remove package = apt-get remove package
# apts purge package = apt-get purge package
# apts add repo = add-apt-repository repo
# apts rem repo = add-apt-repository -r repo
# apts rm oldkernels = special_script
# apts purge removed = apt-get install package
# apts edit = nano /etc/apt/sources.list
# apts search package = apt-cache search package
# apts find file = dpkg --search file
# apts setup package.deb = dpkg --install package.deb
# apts list package = dpkg -L package
# apts edit => editor sources.list (or) sources.list.d/$$-$$.list

case "$1" in
"install"|"update"|"upgrade"|"dist-upgrade"|"download"|"remove"|"autoremove"|"purge"|"clean"|"autoclean")
  apt-get $@
;;
"autopurge")
  apt-get autoremove --purge
;;
"rm")
  case "$2" in
  "oldkernels")
    # http://www.ubuntubuzz.com/2012/02/script-remove-unused-old-kernel.html
    ls /boot/ | grep vmlinuz |
    sed 's@vmlinuz-@linux-image-@g' |
    grep -v `uname -r` |
    while read kern ; do
      apt-get remove $kern -y ; done
    # another way from linuxac.org
    # dpkg -l 'linux-*' | sed '/^ii/!d;/'"$(uname -r | sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d' | xargs sudo apt-get -y purge
  ;;
  "orphan")
    apt-get purge `deborphan` -y
  ;;
  "purge")  # https://ascending.wordpress.com/2007/04/10/apt-tip-purge-removed-packages/
    dpkg -l | awk '/^rc/ {print $2}' | xargs sudo dpkg --purge
  esac
;;

"edit")
  # editor refers to `nano` or `vim`, as configured using `update-alternatives`
  if [ -z "$2" ] ; then
    editor /etc/apt/sources.list
  else
    editor /etc/apt/sources.list.d/$2-$3*.list
  fi
;;
"show"|"search")
  apt-cache $@
;;
"find")
  dpkg --search ${@:2}
;;
"setup")
  dpkg --install ${@:2}
;;
"add")
  add-apt-repository ${@:2}
;;
"rem")
  add-apt-repository -r ${@:2}
;;
"list")
  dpkg -L ${@:2}
;;
esac