#!/bin/bash
# a shell script to generate a setxkbmap line and make it "autostart"
clear
echo "This Will help you make your keyboard multilayout easily. v1.0"
echo
echo "Enter your prefered layouts seprated by comma starting by the main layout, like \"us,ara,ru\""
read ly
echo "Enter your prefered way to toggle the keymap, like \"alt_shift\""
read wy
echo "Enter your prefered led to show that the alternative layout is chosen. like \"scroll\", You can enter \"none\" if you don't want"
read ld
#In the future versions will new features included :)
echo "Genterating now the command..."
kym="setxkbmap -layout \"$ly\" -option \"grp:${wy})_toggle,grp_led:${ld}\""
clear
echo "Line generated, Now making it \"autostart\""

echo "[Desktop Entry]" > "~/.config/autostart/keymap.desktop"
echo "Encoding=UTF-8" >> "~/.config/autostart/keymap.desktop"
echo "Version=0.9.4" >> "~/.config/autostart/keymap.desktop"
echo "Type=Application" >> "~/.config/autostart/keymap.desktop"
echo "Name=KeyMap" >> "~/.config/autostart/keymap.desktop"
echo "Exec=${kym}" >> "~/.config/autostart/keymap.desktop"
echo "StartupNotify=false" >> "~/.config/autostart/keymap.desktop"
echo "Terminal=false" >> "~/.config/autostart/keymap.desktop"
echo "Hidden=false" >> "~/.config/autostart/keymap.desktop"
echo
echo "Added."
exit 0
