#!/bin/bash
# a shell script to generate a setxkbmap line and make it "autostart"
#If you found any bugs or have any suggestions:
#Contact me at : noureddin95 at gmail dot com
#the path '~/' returns error, so replaced by '$HOME/'
if [ -z "$1" ] || [ "$1" == "-h" ]
then
	echo "
 KeySwapper, the easy way to make your keyboard multilingual
  Usage:
    ./keyswap layout1,layout2,..,layoutN switch_keys indicator_led
    example:
    ./keyswap us,ru,ara alt_shift scroll
     To use \"us\" and \"ru\" and \"ara\" layouts, and switch between them (toggle) using \"alt\"
     and \"shift\", and turn on \"scroll\" led when the current layout is NOT the first.
    Note:
     If you didn't choose switch_keys or indicator_led, It\'d be \"alt_shift\" and \"scroll\"
"
	exit
elif [ "$1" == "-a" ] #not mentioned in help because it need some improvements ;)
then
	cat /usr/X11R6/share/X11/xkb/rules/base.lst
fi
kym="setxkbmap -layout \"$1\" -option \"grp:"
if [ -z $2 ]
then
	kym=${kym}"alt_shift_toggle,grp_led:"
else
	kym=${kym}${2}"_toggle,grp_led:"
fi

if [ -z $3 ]
then
	kym=${kym}"scroll\""
else
	kym=${kym}${3}"\""
fi

$kym

mkdir $HOME/.config $HOME/.config/autostart &>/dev/null

echo "[Desktop Entry]
Encoding=UTF-8
Version=0.9.4
Type=Application
Name=KeyMap
Exec=${kym}
StartupNotify=false
Terminal=false
Hidden=false" > "$HOME/.config/autostart/keyswap.desktop"
exit
