#!/bin/bash
#add this script to /etc/rc.local before "exit 0" line, to mount all partitions while booting
a=$(ls /dev/sd*)
for i in $a
do
	udisks --mount $i --mount-options umask=0 &>/dev/null
	udisks --mount $i &>/dev/null
done
