#!/bin/bash
#mount all mountable partitions like udisks but with 'root' account and mount as /media/drive or /C and /D :)
if [ "$1" != "m" -a "$1" != "c" -a "$1" != "mc" ]
then
	echo '''
	This script mounts all mountable partitions like "udisks --mount", but it works only with root. It can mount your partitions as usual, and it also can mount yours at /C, /D and /E :)
	USAGE:
		./mount m  #to mount under /media as usual.
		./mount c  #to mount as /C, /D , etc.
		./mount mc #to mount using both ways.
	'''
else
	all=$(ls /dev/sd*)
	fs=(`cat /etc/mtab|grep '^/'|grep -v 'media'|grep -v '/[CDEFGHIJKLMNOPQRSTUVWXYZ]'|sed 's/[ ].*[^ ].*//'`)
	count=0
	for i in $all
	do
		case "${fs[@]}" in  *"$i"*) ;; *)
			type=`blkid $i | sed 's/.*TYPE="\([^"]\+\)".*/\1/'`
			if [ ${#type} -ne 0 -a "${type}" != "swap" ]
			then
				partition=`echo ${partition} ${i}`
				count=`expr $count + 1`
			fi
		;;  esac
	done
	#all that to avoid disks and extended partitions, we want only mountable partitions
	for dev in $partition
	do	

		label=`blkid $dev | sed 's/.*LABEL="\([^"]\+\)".*/\1/'`
		if [ "${label:0:1}" == "/" ]
		then
			uuid=`blkid $dev | sed 's/.*UUID="\([^"]\+\)".*/\1/'`
			mnt=$uuid
		else
			mnt=$label
		fi

		array=("${array[@]}" "$dev")
		if [ "$1" == "m" -o "$1" == "mc" ]
		then
			mkdir /media/$mnt &>/dev/null
			null=`mount $dev /media/$mnt -o umask=0`
		fi
	done
	win=({A..Z});win=(${win[@]:2:$count})
	for ((i=0;i<$count;i++))
	do
		if [ "$1" == "c" -o "$1" == "mc" ]
		then
			mkdir /${win[$i]} &>/dev/null
			mount ${array[$i]} /${win[$i]} -o umask=0
		fi
	done
fi