#!/bin/bash -x
#mount all mountable partitions like udisks but with 'root' account and mount as /media/drive or /C and /D :)
#Note: All that can be easily done by:
#a=$(ls /dev/sd*)
#for i in $a
#do
#	udisks --mount $i --mount-options umask=0 &>/dev/null
#done
#You will find it in "mountall" in the same directory
#The following script needs some correction in the part of excluding filesystem partitons.
if [ "$1" != "m" ] && [ "$1" != "c" ] && [ "$1" != "mc" ]
then
	echo '''
  This script mounts all mountable partitions like "udisks --mount",
 but it works only with root. It can mount your partitions as usual,
 and it also can mount yours at /C, /D and /E :)
    USAGE:
      ./mount m  #to mount under /media as usual.
      ./mount c  #to mount as /C, /D , etc.
      ./mount mc #to mount using both ways.
'''
else
	all=$(ls /dev/sd*)
	fs=(`cat /etc/mtab|grep '^/'|grep -v 'media'|grep -v '/[CDEFGHIJKLMNOPQRSTUVWXYZ]'|sed 's/[ ].*//'`)
	for i in ${fs[@]}
	do
		if [ "${i:0:9}" == "/dev/disk" ]
		then
			pfs=`echo $pfs /dev/\`ls -l $i|sed 's/.*[ ../../]//'\``
		else
			pfs=`echo $pfs $i`
		fi
	done
	count=0
	for i in ${all[@]}
	do
		case "${pfs[@]}" in *"$i"*) ;; *)
 			type=`blkid $i|sed 's/.*TYPE="\([^"]\+\)".*/\1/'`
			if [ ! -z "${type}" ] && [ "${type}" != "swap" ]
			then
				partition=(${partition} ${i})
			fi

		;; esac
	done
	#all that to avoid disks and extended partitions, we want only mountable partitions
	for dev in $partition
	do

		label=`blkid $dev|sed 's/.*LABEL="\([^"]\+\)".*/\1/'`
		if [ "${label:0:1}" == "/" ]
		then
			uuid=`blkid $dev|sed 's/.*UUID="\([^"]\+\)".*/\1/'`
			mnt=$uuid
		else
			mnt=$label
		fi

		if [ "$1" == "m" ] || [ "$1" == "mc" ]
		then
			mkdir /media/$mnt &>/dev/null
			mount $dev /media/$mnt -o umask=0 &>/dev/null
		fi
	done
	if [ "$1" == "c" ] || [ "$1" == "mc" ]
	then
		win=({C..Z})
		for ((i=0;i<${#parition};i++))
		do
			mkdir /${win[$i]} &>/dev/null
			mount ${partition[$i]} /${win[$i]} -o umask=0 &>/dev/null
		done
	fi
fi