#!/bin/bash
#From: https://culturedcode.com/things/wiki/index.php/Syncing_Things_with_git_and_Launchd
#TODO: Support commit msg with spaces and without (")s

if [ "$1" == "-h" ] || [ "$1" == "--help" ]
then
	echo "
 GitSync
   A simple and small script to sync your remote git repo with your local one
   Just edit local repo and get remote one synchronized
Installation
  sudo cp gs /usr/bin
Usage
  Form: gs [local_repo] [commit_msg]
  *Note: You should have already installed 'git' and git repo
  If you are already in your local repo, just execute 'gs' or 'gs .' and
   wait to calculate files and enter your username and password.
  If you are in another directory and want to sync your git, just execute 'gs'
   followed by your local git directory.
  You can use specified commit message instead of 'Updated' followed by the date.
  NOTE: 'local_repo' and 'commit_msg' must be included in \" and \" if contain spaces

Taken from https://culturedcode.com/things/wiki/index.php/Syncing_Things_with_git_and_Launchd and modified by me :)
"
exit
fi

if [ "$1" != "" ];then
	cd $1;fi
git add *
git pull origin master
if [ -z "$2" ]
then
	git commit -a -m "Update - `date +'%a %d/%m/%Y %R'`"
else
	git commit -a -m "${@:2}"
fi
git push origin master
