#!/bin/bash
#Install by "sudo cp blocker /usr/sbin;sudo touch /etc/modprobe.d/blacklist"
blst='/etc/modprobe.d/blacklist'

if [ "$1" != "b" -o "$1" != "block" -o "$1" != "a" -o "$1" != "allow" ]
then
	echo '''
	Kernel Module Blocker for Unix-like systems (Now Debian Only)
	 You can use this script to block any kernel module.
	 It -Simply- add it to the blacklist, And removes it when you "allow".
	 Usage:
		b, block [mod] #to block any module
		a, allow [mod] #to allow any blocked module
		any thing else #to show this help ;)		
	'''	
fi
arr=( $@ )

for a in ${arr[@]:1}
do		
	inbls=`cat $blst|grep $a` #In Blacklist
	found=`lsmod|grep $a` #In Modules

	if [ "$1" == "b" -o "$1" == "block" ]	
	then
		if [ $found == "" ];then
			echo "$@ is not found on system"
		elif [ $inbls != "" ];then
			echo "$@ is already blocked"
		else
			echo "blacklist" $a >> "$blst"		
		fi
	elif [ "$1" == "a" -o "$1" == "allow" ]
	then
		if [ $found == "" ];then
			echo "$@ is not found on system"
		elif [ $inbls == "" ];then
			echo "$@ is not blocked"
		else
			sed "/$a/d" $blst > ${blst}.save
			mv ${blst}.save ${blst}
		fi

	fi
done
exit