#!/bin/bash

#Steps:
#read sQ
#for i in 001 114
#mv $i.mp3 $i-${sQ[$i]}.mp3

sq=`cat sQ`
sq=( 0 $sq ) #to start with 1 not 0
for ((i=1;i<115;i++))
do
	if [ ${#i} -lt 3 ]
	then
		n=`printf "0%.0s" $(seq \`expr 3 - ${#i}\`)`$i #change 1 to 001 and 25 to 025
	else
		n=$i
	fi
	mv $n.mp3 $n-${sq[$i]}.mp3
done
# "آل_عمران" بدون مسافة لتجنب حدوث مشاكل :)