#!/bin/bash
# Make any application you want "autostart"
# If you found any bugs or have any suggestions:
# Contact me at : noureddin95 at gmail dot com

function echohelp {
	if [ "$hb" != 1 ] ; then  # helpboolean, to avoid printing help more than one time
		echo "
 AutoStart, the easy way to make you any application autostart
 for the current user
  Usage:
   Install 'AutoStart' to your system:
     ./autostart -i
   Add app to 'autostart':
     autostart -a app_name
   Remove app from 'autostart'
     autostart -r app_name
   List all apps on system:
     autostart -l
   List the autostarting apps:
     autostart -la
"
	hb=1
	fi
}

if [ -z "$1" ]
then
	echohelp
	exit
fi

mkdir $HOME/.config $HOME/.config/autostart &>/dev/null

appdir="/usr/share/applications"
atodir="$HOME/.config/autostart"

for a in $@
do
	if [ "$a" == "-a" ]  # add to autostart
	then
		case="add"
		continue
	elif [ "$a" == "-r" ]  # remove from autostart
	then
		case="remove"
		continue
	elif [ "$a" == "-l" ]  # list all apps on system
	then
		ls $appdir | sed 's/.desktop//g'
		continue
	elif [ "$a" == "-la" ]  # list all autostart apps
	then
		ls $atodir | sed 's/.desktop//g'
		continue
	elif [ "$a" == "-i" ]  # install
	then
		cp $0 /usr/bin  # used $0 not 'autostart' to install/copy it whatever its name was
		echo "AutoStart Installed"
		continue
	elif [ "${a:0:1}" == "-" ]  # if first letter is dash, to avoid any non-understood options
	then
		echohelp
		continue
	fi
	
	if [ "$case" != "add" ] && [ "$case" != "remove" ]  # if entered appname without typing -a or -r before
	then
		echohelp
		continue
	fi

	if [ "$case" == "add" ]
	then
		if [ -e "$appdir/$a.desktop" ]
		then
			cp "$appdir/$a.desktop $atodir"
			echo "$a added to autostart"
		else
			echo "$a not found on system, try \"autostart -l\""
		fi
	else
		if [ -e "$atodir/$a.desktop" ]
		then
			rm "$atodir/$a.desktop"
			echo "$a removed from autostart"
		else
			echo "$a not found in autostart, try \"autostart -la\""
		fi
	fi
done
exit
