#!/bin/bash
# Converting .grx files (getright list file) to a wget script ;)
# Usage: grx2wget /path/to/file.grx
# Before Using: correct the file encoding (if non-latin) and line ending (to unix, "LF")
# How to work:
#  make a temp file to work on
#  read every line in the original grx file
#  if the line begin with "URL:" make it "wget $URL -O "
#  and if it begins with "File:" continue the last line with it
#  but make C:, D:, .. to /home/user and change every \ to /
#  remove temp file
#  make directories
# You may test it: http://way2allah.com/khotab-series-638.htm
# You may take a look at this *_^ :
#   http://www.linuxac.org/forum/threads/63002-%D9%85%D8%AD%D9%88%D9%84-grx-%D9%84%D8%AA%D8%AD%D9%88%D9%8A%D9%84-%D9%85%D9%84%D9%81%D8%A7%D8%AA-getright-%D8%A5%D9%84%D9%89-wget
sed 's|\\|\\\\|g' "$@" > /tmp/tempfile.grx

cat /tmp/tempfile.grx | while read line
do
    case "$line" in
    'URL:'*)
        echo -n "wget -c ${line:5} -O " >> /tmp/tempwgetfile
    ;;
    'File:'*)
        echo "\"${line:6}\"" | sed 's|\\|/|g' | sed "s|[a-Z]:|$HOME|g"  >> /tmp/tempwgetfile
    ;;
    esac
done

# Make directories
sed 's/.*"\([^"]\+\)".*/\1/' /tmp/tempwgetfile | # get the adressess only
sed 's/\/[^\/]\+$//' |				 # remove the file name to keep the directories only
uniq |						 # remove duplicated
grep -v '#!' > /tmp/dirlist			 # remove the '#!/bin/sh' line and store it in a temp file


echo '#!/bin/sh' > "${@}.sh"	# put the shebang line
echo >> "${@}.sh"		# put an empty line
cat /tmp/dirlist | uniq | while read path
do echo "mkdir -p \"$path\" 2>/dev/null" >> "${@}.sh"
done				# put the 'mkdir' lines

echo >> "${@}.sh"		# put an empty line

cat /tmp/tempwgetfile >> "${@}.sh" # put the 'wget $URL' lines

chmod +x "${@}.sh" # make it executable
# Note; Because of using "${@}.sh", the produced shell is written in the same directory of the grx file

rm /tmp/tempwgetfile
rm /tmp/tempfile.grx
rm /tmp/dirlist