#!/bin/bash

# Lock and Unloack a directory with a password
# Should run with the root
# You may chmod +x and chmod +s this script after chmod 0700 it
# You may SHC it ;)

# Steps:
#  1- Check Permissions of the directory
#  2- If Not 000 then chmod 000 it
#  3- Else: ask for the password
#  4- chmod 777 it
#  5- launch the start script

password=''
directory='' # without '/' at the end
script=''

#  1- Check Permissions of the directory
permissions=`ls -al \`echo $directory | sed 's/\/[^\/]\+$//'\` | grep "\`echo $directory | sed 's|.*\/||' | sed 's/\./\\\./'\`" | awk '{ print $1 }'`

#  2- If Not 000 then chmod 000 it
if [ "$permissions" != "d---------" ] ; then
	chmod 0000 -R $directory ; exit ; fi

#  3- Else: ask for the password
pw=`zenity --password`
if [ "$pw" != "$password" ] ; then
	exit
fi

#  4- chmod 777 it
chmod 0777 -R $directory

#  5- launch the start script
$script &
exit
