#!/bin/bash

# Shutdown, Restart, Suspend, or Hibernate the computer, and more, without sudo!
# Forked from https://gist.github.com/988104 to support delaying and more :)
# You may take a look at: https://github.com/noureddin/easy-shutdown

usage() {
    echo "
 UserPower is a simple way to Shutdown, Restart, Suspend
  or Hibernate the Computer, and more, without being root
  or using difficult GUI.
   Usage:
  $0 logout|lockscreen|switchuser|shutdown|restart|suspend|hibernate [minutes]
"
    exit
}

if [ -z $# ] ; then
	usage
elif [ -n "${@:2}" ] ; then
	case "${@:2}" in
	*"h"*|*"m"*|*"s"*) # 1h 5m 2s (if h, m or s found)
		sleep ${@:2} 2>/dev/null || ( echo 'Timing Error' >&2 && exit 2 )
		;;
	*":"*) # 15:00 (if ':' found)
		# TODO: needs some improvements ;)
		h=$((`echo ${@:2} | sed 's/:.*//'` - `date +%H`))
		if [ $h -le 0 ] ; then
			h=$(( $h + 24 )) ; fi
		m=$((`echo ${@:2} | sed 's/.*://'` - `date +%M`))
		if [ $m -lt 0 ] ; then
			m=$(( $m + 60 )) ; fi
		sleep ${h}h ${m}m 2>/dev/null || ( echo 'Timing Error' >&2 && exit 2 )
		;;
	*[0-9]*) # 5 (if contain numbers)
		sleep ${@:2}m 2>/dev/null || ( echo 'Timing Error' >&2 && exit 2 )
		;;
	esac
fi

THINGY_UPOWER="dbus-send --system --print-reply --dest=org.freedesktop.UPower /org/freedesktop/UPower"
THINGY_CONSOLEKIT="dbus-send --system --print-reply --dest=org.freedesktop.ConsoleKit /org/freedesktop/ConsoleKit/Manager"
case $1 in
logout)
	echo Going to $1 now ...
#    killall `w -f | grep tty | awk '{print $7 }'` >/dev/null
    gnome-session-save --kill --silent >/dev/null || mate-session-save --kill --silent >/dev/null ;  killall -u $USER >/dev/null # This is better :P
#   Problems might happen when use 'killall -u' with gnome or mate
;;
lockscreen)
	echo Going to $1 now ...
    for i in `ls /usr/bin/*screensaver`; do if [ -n `pidof $i` ] && [ -e "${i}-command" ] ; then ${i}-command -l ; fi ; done >/dev/null
;;
switchuser)
	echo Going to $1 now ...
#     for i in `ls /usr/sbin/*dm`; do if [ -n "`pidof $i`" ] ; then case $i in
#     /usr/sbin/lightdm)dm-tool switch-to-greeter;;
#     /usr/sbin/mdm)mdmflexiserver;;
#     /usr/sbin/gdm)gdmflexiserver;; # Not tested yet
#     *)echo "Sorry, Your Display Manager is not supported yet.";;
#     esac
#     fi ;done
    dm-tool switch-to-greeter 2>/dev/null || mdmflexiserver 2>/dev/null || gdmflexiserver 2>/dev/null
# MayBe: gdm-control
    # Simplicity is Good ;)
;;
shutdown)
	echo Going to $1 now ...
    $THINGY_CONSOLEKIT org.freedesktop.ConsoleKit.Manager.Stop >/dev/null
;;
restart)
        echo Going to $1 now ...
    $THINGY_CONSOLEKIT org.freedesktop.ConsoleKit.Manager.Restart >/dev/null
;;
suspend)
        echo Going to $1 now ...
    $THINGY_UPOWER org.freedesktop.UPower.Suspend >/dev/null
;;
hibernate)
        echo Going to $1 now ...
    $THINGY_UPOWER org.freedesktop.UPower.Hibernate >/dev/null
;;
*)
    usage
;;
esac

exit
